# Generated by Django 6.0 on 2026-01-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatteStamm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. W1000 ST9 19', max_length=80, unique=True)),
                ('laenge_mm', models.PositiveIntegerField(default=2800, editable=False)),
                ('breite_mm', models.PositiveIntegerField(default=2070, editable=False)),
                ('staerke_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('preis_eur_pro_qm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Stammplatte',
                'verbose_name_plural': 'Stammplatten',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Beschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artikelnummer', models.CharField(max_length=80, unique=True)),
                ('hersteller', models.CharField(max_length=80)),
                ('preis_eur_pro_stk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regal', models.CharField(max_length=50)),
                ('platz', models.CharField(max_length=50)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Beschlag',
                'verbose_name_plural': 'Beschläge',
                'ordering': ('hersteller', 'name', 'artikelnummer'),
                'indexes': [models.Index(fields=['artikelnummer'], name='lager_besch_artikel_675f0f_idx'), models.Index(fields=['hersteller'], name='lager_besch_herstel_2c272d_idx'), models.Index(fields=['regal', 'platz'], name='lager_besch_regal_ec5313_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeschlagBuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ZUGANG', 'Zugang'), ('ABGANG', 'Abgang'), ('RESERVIERT', 'Reserviert'), ('FREIGABE', 'Freigabe'), ('KORREKTUR', 'Korrektur')], max_length=20)),
                ('auftragsnummer', models.CharField(blank=True, help_text='Pflicht bei Reserviert/Freigabe (Freitext).', max_length=80)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('menge_stk', models.IntegerField(help_text='Ganze Stückzahl. Korrektur darf negativ sein.')),
                ('beschlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='lager.beschlag')),
            ],
            options={
                'verbose_name': 'Buchung Beschlag',
                'verbose_name_plural': 'Buchungen Beschläge',
                'ordering': ('-datum',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='z.B. W1000 ST9', max_length=80)),
                ('staerke_mm', models.DecimalField(decimal_places=1, max_digits=3)),
                ('breite_mm', models.PositiveIntegerField()),
                ('rollenlaenge_lfm', models.IntegerField(choices=[(50, '50 lfm'), (75, '75 lfm'), (150, '150 lfm')])),
                ('preis_eur_pro_lfm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regal', models.CharField(max_length=50)),
                ('platz', models.CharField(max_length=50)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Kante',
                'verbose_name_plural': 'Kanten',
                'ordering': ('code', 'staerke_mm', 'breite_mm'),
                'indexes': [models.Index(fields=['code'], name='lager_kante_code_a07812_idx'), models.Index(fields=['regal', 'platz'], name='lager_kante_regal_eb32cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'staerke_mm', 'breite_mm'), name='uniq_kante_code_staerke_breite')],
            },
        ),
        migrations.CreateModel(
            name='KantenBuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ZUGANG', 'Zugang'), ('ABGANG', 'Abgang'), ('RESERVIERT', 'Reserviert'), ('FREIGABE', 'Freigabe'), ('KORREKTUR', 'Korrektur')], max_length=20)),
                ('auftragsnummer', models.CharField(blank=True, help_text='Pflicht bei Reserviert/Freigabe (Freitext).', max_length=80)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('menge_lfm', models.IntegerField(help_text='Ganze lfm. Korrektur darf negativ sein.')),
                ('kante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='lager.kante')),
            ],
            options={
                'verbose_name': 'Buchung Kante',
                'verbose_name_plural': 'Buchungen Kanten',
                'ordering': ('-datum',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatteStammBuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ZUGANG', 'Zugang'), ('ABGANG', 'Abgang'), ('RESERVIERT', 'Reserviert'), ('FREIGABE', 'Freigabe'), ('KORREKTUR', 'Korrektur')], max_length=20)),
                ('auftragsnummer', models.CharField(blank=True, help_text='Pflicht bei Reserviert/Freigabe (Freitext).', max_length=80)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('menge_stk', models.IntegerField(help_text='Ganze Stückzahl. Korrektur darf negativ sein.')),
                ('platte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='lager.plattestamm')),
            ],
            options={
                'verbose_name': 'Buchung Stammplatte',
                'verbose_name_plural': 'Buchungen Stammplatten',
                'ordering': ('-datum',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restplatte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=80)),
                ('laenge_mm', models.PositiveIntegerField()),
                ('breite_mm', models.PositiveIntegerField()),
                ('regal', models.CharField(max_length=50)),
                ('platz', models.CharField(max_length=50)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
                ('stamm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restplatten', to='lager.plattestamm')),
            ],
            options={
                'verbose_name': 'Restplatte',
                'verbose_name_plural': 'Restplatten',
                'ordering': ('code', 'regal', 'platz'),
            },
        ),
        migrations.CreateModel(
            name='RestplatteBuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ZUGANG', 'Zugang'), ('ABGANG', 'Abgang'), ('RESERVIERT', 'Reserviert'), ('FREIGABE', 'Freigabe'), ('KORREKTUR', 'Korrektur')], max_length=20)),
                ('auftragsnummer', models.CharField(blank=True, help_text='Pflicht bei Reserviert/Freigabe (Freitext).', max_length=80)),
                ('bemerkung', models.CharField(blank=True, max_length=200)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('menge_stk', models.IntegerField(help_text='Ganze Stückzahl. Korrektur darf negativ sein.')),
                ('restplatte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='lager.restplatte')),
            ],
            options={
                'verbose_name': 'Buchung Restplatte',
                'verbose_name_plural': 'Buchungen Restplatten',
                'ordering': ('-datum',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='restplatte',
            index=models.Index(fields=['code'], name='lager_restp_code_3c41da_idx'),
        ),
        migrations.AddIndex(
            model_name='restplatte',
            index=models.Index(fields=['regal', 'platz'], name='lager_restp_regal_332c17_idx'),
        ),
    ]
